export const IPC = {
  SESSION_PING: 'session:ping',
  /**
   * Replaces the old unconditional `session:start` (Workstream D) — the
   * approval-mode-aware entry point every real send now goes through. See
   * `SessionManager.requestStart`/`confirmStart`/`cancelStart`.
   */
  SESSION_REQUEST_START: 'session:request-start',
  SESSION_CONFIRM_START: 'session:confirm-start',
  SESSION_CANCEL_START: 'session:cancel-start',
  SESSION_KILL: 'session:kill',
  SESSION_GRANT_AUTONOMY: 'session:grant-autonomy',
  SESSION_HISTORY_LIST: 'session:history-list',
  SESSION_EVENT: 'session:event',
  PROJECT_ADD: 'project:add',
  PROJECT_LIST: 'project:list',
  PROJECT_REMOVE: 'project:remove',
  PROJECT_SET_PERMISSIONS: 'project:set-permissions',
  SKILLS_LIST: 'skills:list',
  SKILLS_SET_ENABLED: 'skills:set-enabled',
  SKILLS_RECOMMEND: 'skills:recommend',
  SKILLS_CREATE: 'skills:create',
  MARKETPLACE_LIST: 'marketplace:list',
  MARKETPLACE_BROWSE: 'marketplace:browse',
  MARKETPLACE_INSTALL: 'marketplace:install',
  MARKETPLACE_UNINSTALL: 'marketplace:uninstall',
  HARNESS_CRITERIA_SET: 'harness:criteria-set',
  HARNESS_PREVIEW_DETECT: 'harness:preview-detect',
  HARNESS_PREVIEW_SET: 'harness:preview-set',
  HARNESS_RUN_START: 'harness:run-start',
  HARNESS_RUN_LIST: 'harness:run-list',
  HARNESS_JEV_SET_FEATURES: 'harness:jev-set-features',
  HARNESS_TEST_DETECT: 'harness:test-detect',
  HARNESS_TEST_SET: 'harness:test-set',
  HARNESS_CRITERION_PREFILTER: 'harness:criterion-prefilter',
  PREVIEW_PANEL_START: 'preview-panel:start',
  PREVIEW_PANEL_STOP: 'preview-panel:stop',
  PREVIEW_PANEL_SET_BOUNDS: 'preview-panel:set-bounds',
  PREVIEW_PANEL_HIDE: 'preview-panel:hide',
  PREVIEW_PANEL_STATUS: 'preview-panel:status',
  SETTINGS_TYPESAFE_STATUS: 'settings:typesafe-status',
  SETTINGS_TYPESAFE_SET_KEY: 'settings:typesafe-set-key',
  SETTINGS_TYPESAFE_CLEAR_KEY: 'settings:typesafe-clear-key',
} as const
